create table roles (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
);
create table users (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    username varchar(255) NOT NULL UNIQUE
);

create table users_roles (
    user_id int8 not null,
    role_id int8 not null,
    constraint user_role PRIMARY KEY (user_id, role_id)
);

alter table if exists users_roles add constraint role_users_roles foreign key (role_id) references roles;
alter table if exists users_roles add constraint user_users_roles foreign key (user_id) references users;